"""add relationship message to user

Revision ID: 0dd6c5c16079
Revises: eeca48af3c5b
Create Date: 2021-03-02 02:55:46.415870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd6c5c16079'
down_revision = 'eeca48af3c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_messages', sa.Column('author', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'app_messages', 'app_users', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_messages', type_='foreignkey')
    op.drop_column('app_messages', 'author')
    # ### end Alembic commands ###
