"""bytes of data to text

Revision ID: 32c25bc6ae99
Revises: 67818fa15fc1
Create Date: 2021-03-02 20:48:23.795054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32c25bc6ae99'
down_revision = '67818fa15fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_attachments', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_attachments', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
