"""create like table

Revision ID: 638254862657
Revises: e88cad0d70e7
Create Date: 2021-03-03 08:27:52.609139

"""
from alembic import op
import sqlalchemy as sa

from db.alembic.helpers import Sequence
likes_id_seq = Sequence("app_likes_id_seq")

# revision identifiers, used by Alembic.
revision = '638254862657'
down_revision = 'e88cad0d70e7'
branch_labels = None
depends_on = None


def upgrade():
    likes_id_seq.upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_likes',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('app_likes_id_seq')"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['app_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_likes')
    # ### end Alembic commands ###

    likes_id_seq.downgrade()
