"""attachment with message

Revision ID: 67818fa15fc1
Revises: 0dd6c5c16079
Create Date: 2021-03-02 04:37:08.331352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67818fa15fc1'
down_revision = '0dd6c5c16079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_attachments', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'app_attachments', 'app_messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_attachments', type_='foreignkey')
    op.drop_column('app_attachments', 'message_id')
    # ### end Alembic commands ###
