"""bytes of data to text2

Revision ID: e88cad0d70e7
Revises: 32c25bc6ae99
Create Date: 2021-03-02 20:49:39.439925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88cad0d70e7'
down_revision = '32c25bc6ae99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_attachments', sa.Column('data', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_attachments', 'data')
    # ### end Alembic commands ###
