"""create users table

Revision ID: eba4c976005b
Revises: 
Create Date: 2021-03-01 21:44:23.746257

"""
from alembic import op
import sqlalchemy as sa

from db.alembic.helpers import Sequence
users_id_seq = Sequence("app_users_id_seq")

# revision identifiers, used by Alembic.
revision = 'eba4c976005b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    users_id_seq.upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('app_users_id_seq')"), nullable=False),
    sa.Column('login', sa.String(length=63), nullable=True),
    sa.Column('password', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_users')
    # ### end Alembic commands ###
    users_id_seq.downgrade()
