"""create messages with attachments

Revision ID: eeca48af3c5b
Revises: eba4c976005b
Create Date: 2021-03-02 02:17:08.412837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db.alembic.helpers import remove_enum, Sequence

attachments_id_seq = Sequence("app_attachments_id_seq")
messages_id_seq = Sequence("app_messages_id_seq")

# revision identifiers, used by Alembic.
revision = 'eeca48af3c5b'
down_revision = 'eba4c976005b'
branch_labels = None
depends_on = None


def upgrade():
    attachments_id_seq.upgrade()
    messages_id_seq.upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_attachments',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('app_attachments_id_seq')"), nullable=False),
    sa.Column('kind', sa.Enum('text', 'media', 'link', name='attachmentkind'), nullable=True),
    sa.Column('data', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_messages',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('app_messages_id_seq')"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_messages')
    op.drop_table('app_attachments')
    # ### end Alembic commands ###

    remove_enum("attachmentkind")
    attachments_id_seq.downgrade()
    messages_id_seq.downgrade()
